on:
  push:
    branches: [ main, "**workflow**" ]
  pull_request:
    branches: [ main, "**workflow**" ]

  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup python 3.8+
        uses: actions/setup-python@v4.6.1
        with:
          python-version: "^3.8"
          cache: pip
          cache-dependency-path: ./requirements.txt
      - name: Run tests
        run: |
          chmod +x ./run_tests.sh
          ./run_tests.sh
          
